"""
Django settings for savannah-backend-dev-challenge project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os

from pathlib import Path

####################################################################################################
# File system and misc
####################################################################################################
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


####################################################################################################
# Django Dev Panel recommendations and other security
####################################################################################################

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
CSRF_USE_SESSIONS = False


####################################################################################################
# Installed Apps
####################################################################################################

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third Party Apps
    'drf_spectacular',
    'dynamic_rest',
    'oauth2_provider',
    'oidc_provider',
    'rest_framework',
    'rest_framework.authtoken',
    # Project Apps
    'apps.core.apps.CoreConfig',
    'apps.shop.apps.ShopConfig'
]


####################################################################################################
# Middleware
####################################################################################################

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


####################################################################################################
# Core Django config
####################################################################################################

APPEND_SLASH = True
BASE_URL = "http://localhost:8000"
INTERNAL_IPS = ["127.0.0.1"]
ROOT_URLCONF = "config.urls"
SECRET_KEY = os.environ['SECRET_KEY']
WSGI_APPLICATION = "config.wsgi.application"


####################################################################################################
# Template
####################################################################################################

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['assets/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


####################################################################################################
# Auth
####################################################################################################

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/api/'

LOGIN_URL = '/accounts/login/'


####################################################################################################
# Translations and Locales
####################################################################################################

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_L10N = True
USE_TZ = True


####################################################################################################
# Static assets
####################################################################################################

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets' / 'static'
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'


####################################################################################################
# DRF
####################################################################################################

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'oidc_auth.authentication.JSONWebTokenAuthentication',
        'oidc_auth.authentication.BearerTokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'dynamic_rest.renderers.DynamicBrowsableAPIRenderer'
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'HTML_SELECT_CUTOFF': 1000
}


####################################################################################################
# DOT
####################################################################################################

OAUTH2_PROVIDER = {
    'SCOPES': {
        'customer:read': 'Access your data',
        'order:read': 'Access your orders',
        'order:write': 'Create new orders and modify your existing orders',
    }
}


####################################################################################################
# OIDC AUTH
####################################################################################################

OIDC_AUTH = {
    'OIDC_ENDPOINT': BASE_URL + '/accounts/'
}


####################################################################################################
# Africa's Talking API
####################################################################################################

AFRICASTALKING_API = {
    'API_KEY': os.environ['AFRICASTALKING_API_KEY'],
    'USERNAME': os.environ['AFRICASTALKING_USERNAME'],
    'SMS_SENDER_ID': os.environ['AFRICASTALKING_SENDER_ID'],
    'SMS_SHORT_CODE': os.environ['AFRICASTALKING_SHORT_CODE']
}


####################################################################################################
# Drf Spectacular
####################################################################################################

SPECTACULAR_SETTINGS = {
    'COMPONENT_SPLIT_REQUEST': True,
    'TITLE': 'Beverage Shop REST Service',
    'DESCRIPTION': (
        'A simple REST API that allows customers of a beverage shop to make '
        'beverage orders.'
    ),
    'SCHEMA_PATH_PREFIX': r'/api/',
    'VERSION': '1.2.0',
}
